gdpr/urls.py
# -*- encoding: utf-8 -*-
from django.urls import re_path

from .views import (
    ConsentCreateView,
    ConsentDetailView,
    ConsentListView,
    ConsentUpdateView,
    ConsentUserListView,
    FormSettingsCreateView,
    FormSettingsListView,
    FormSettingsUpdateView,
    FrequencyCreateView,
    FrequencyDeleteView,
    FrequencyListView,
    FrequencyUpdateView,
    MethodCreateView,
    MethodDeleteView,
    MethodListView,
    MethodUpdateView,
    report_consent_user_download,
    UserConsentAuditListView,
    UserConsentCreateView,
    UserConsentUpdateView,
)


urlpatterns = [
    re_path(
        r"^consent/(?P<pk>\d+)/$",
        view=ConsentDetailView.as_view(),
        name="gdpr.consent.detail",
    ),
    re_path(
        r"^consent/$",
        view=ConsentListView.as_view(),
        name="gdpr.consent.list",
    ),
    re_path(
        r"^consent/create/$",
        view=ConsentCreateView.as_view(),
        name="gdpr.consent.create",
    ),
    re_path(
        r"^consent/(?P<pk>\d+)/update/$",
        view=ConsentUpdateView.as_view(),
        name="gdpr.consent.update",
    ),
    re_path(
        r"^consent/(?P<pk>\d+)/user/$",
        view=ConsentUserListView.as_view(),
        name="gdpr.consent.user.list",
    ),
    re_path(
        r"^consent/(?P<pk>\d+)/user/download/$",
        view=report_consent_user_download,
        name="gdpr.consent.user.download",
    ),
    re_path(
        r"^form/settings/create/$",
        view=FormSettingsCreateView.as_view(),
        name="gdpr.form.settings.create",
    ),
    re_path(
        r"^form/settings/$",
        view=FormSettingsListView.as_view(),
        name="gdpr.form.settings.list",
    ),
    re_path(
        r"^form/settings/(?P<pk>\d+)/update/$",
        view=FormSettingsUpdateView.as_view(),
        name="gdpr.form.settings.update",
    ),
    re_path(
        r"^frequency/create/$",
        view=FrequencyCreateView.as_view(),
        name="gdpr.frequency.create",
    ),
    re_path(
        r"^frequency/(?P<pk>\d+)/delete/$",
        view=FrequencyDeleteView.as_view(),
        name="gdpr.frequency.delete",
    ),
    re_path(
        r"^frequency/$",
        view=FrequencyListView.as_view(),
        name="gdpr.frequency.list",
    ),
    re_path(
        r"^frequency/(?P<pk>\d+)/update/$",
        view=FrequencyUpdateView.as_view(),
        name="gdpr.frequency.update",
    ),
    re_path(
        r"^method/create/$",
        view=MethodCreateView.as_view(),
        name="gdpr.method.create",
    ),
    re_path(
        r"^method/(?P<pk>\d+)/delete/$",
        view=MethodDeleteView.as_view(),
        name="gdpr.method.delete",
    ),
    re_path(
        r"^method/$",
        view=MethodListView.as_view(),
        name="gdpr.method.list",
    ),
    re_path(
        r"^method/(?P<pk>\d+)/update/$",
        view=MethodUpdateView.as_view(),
        name="gdpr.method.update",
    ),
    re_path(
        r"^user/consent/(?P<pk>\d+)/audit/$",
        view=UserConsentAuditListView.as_view(),
        name="gdpr.user.consent.audit.list",
    ),
    re_path(
        r"^user/(?P<pk>\d+)/consent/create/$",
        view=UserConsentCreateView.as_view(),
        name="gdpr.user.consent.create",
    ),
    re_path(
        r"^user/consent/(?P<pk>\d+)/update/$",
        view=UserConsentUpdateView.as_view(),
        name="gdpr.user.consent.update",
    ),
]

gdpr/models.py
# -*- encoding: utf-8 -*-
import secrets

from datetime import date
from dateutil.relativedelta import relativedelta
from django.apps import apps
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone
from reversion import revisions as reversion

from base.model_utils import (
    copy_model_instance_to,
    TimedCreateModifyDeleteModel,
)
from base.singleton import SingletonModel


def get_contact_model():
    return apps.get_model(settings.CONTACT_MODEL)


class GdprError(Exception):
    def __init__(self, value):
        Exception.__init__(self)
        self.value = value

    def __str__(self):
        return repr("%s, %s" % (self.__class__.__name__, self.value))


class FrequencyManager(models.Manager):
    def create_frequency(self, slug, name):
        obj = self.model(slug=slug, name=name)
        obj.save()
        return obj

    def current(self):
        return self.model.objects.exclude(deleted=True)

    def init_frequency(self, slug, name):
        try:
            obj = self.model.objects.get(slug=slug)
            obj.name = name
            obj.save()
        except self.model.DoesNotExist:
            obj = self.create_frequency(slug, name)
        return obj


class Frequency(TimedCreateModifyDeleteModel):
    """Communication frequency e.g. monthly, weekly."""

    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    objects = FrequencyManager()

    class Meta:
        ordering = ["name"]
        verbose_name = "Frequency"
        verbose_name_plural = "Frequencies"

    def __str__(self):
        return "{}".format(self.name)


reversion.register(Frequency)


class GdprSettings(SingletonModel):

    can_download_csv = models.BooleanField(
        default=False,
        help_text="Allow a member of staff to download a CSV of consents",
    )
    show_frequency = models.BooleanField(
        default=False, help_text="Display the frequency option"
    )
    show_method = models.BooleanField(
        default=False, help_text="Display the method option"
    )

    class Meta:
        verbose_name = "GDPR Settings"
        verbose_name_plural = "GDPR Settings"

    def __str__(self):
        return "GDPR Settings: Can download CSV: {}".format(
            self.can_download_csv
        )


reversion.register(GdprSettings)


class MethodManager(models.Manager):
    """Communication methods.

    .. warning:: Do not create an init method or make the name unique.
                 We expect the different consent types to create communication
                 methods with the same name e.g.  ``Post``, ``email``.

    """

    def create_method(self, slug, name):
        obj = self.model(slug=slug, name=name)
        obj.save()
        return obj

    def current(self):
        return self.model.objects.exclude(deleted=True)

    def init_method(self, slug, name):
        try:
            obj = self.model.objects.get(slug=slug)
            obj.name = name
            obj.save()
        except self.model.DoesNotExist:
            obj = self.create_method(slug, name)
        return obj


class Method(TimedCreateModifyDeleteModel):
    """GDPR communication method e.g. post, email, phone."""

    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    objects = MethodManager()

    class Meta:
        ordering = ["name"]
        verbose_name = "Communication method"
        verbose_name_plural = "Communication methods"

    def __str__(self):
        return "{}".format(self.name)


reversion.register(Method)


class ConsentManager(models.Manager):
    def create_consent(
        self,
        slug,
        name,
        message,
        show_checkbox,
        consent_required=None,
        no_consent_message=None,
    ):
        if consent_required is None:
            consent_required = False
        if no_consent_message is None:
            no_consent_message = ""
        obj = self.model(
            slug=slug,
            name=name,
            message=message,
            show_checkbox=show_checkbox,
            consent_required=consent_required,
            no_consent_message=no_consent_message,
        )
        obj.save()
        return obj

    def current(self):
        return self.model.objects.exclude(deleted=True)

    def get_consent(self, slug):
        try:
            return self.model.objects.get(slug=slug)
        except self.model.DoesNotExist:
            raise GdprError("Consent '{}' does not exist".format(slug))

    def init_consent(
        self,
        slug,
        name,
        message,
        show_checkbox,
        consent_required=None,
        no_consent_message=None,
    ):
        if consent_required is None:
            consent_required = False
        if no_consent_message is None:
            no_consent_message = ""
        try:
            obj = self.model.objects.get(slug=slug)
            obj.name = name
            obj.message = message
            obj.show_checkbox = show_checkbox
            obj.consent_required = consent_required
            obj.no_consent_message = no_consent_message
            obj.save()
        except self.model.DoesNotExist:
            obj = self.create_consent(
                slug,
                name,
                message,
                show_checkbox,
                consent_required,
                no_consent_message,
            )
        return obj


class Consent(TimedCreateModifyDeleteModel):
    """GDPR consent type.

    From:
    GDPR - Development
    https://docs.google.com/spreadsheets/d/1WR1D0zzHO4UPoFxrJ2mx4Gd34PnHJ9K6I-0ZEuPW0u4/edit?usp=sharing

    Your database will be updated so you can track whether a user has given
    consent for the use of their personal data.

    The database will be able to record consent for areas of interest

    1. e.g. marketing campaigns for particular products.
    2. types of communication e.g. contact me via email or post
    3. frequency e.g. once a month or once a year

    Question ref 2 and 3:

    Is the type of communication and frequency related to the user i.e. (one
    record per user) or do these preferences need to be recorded for every
    communication campaign?

    TODO

    - If possible, include a link to the privacy notice with the message.

    """

    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    frequency = models.ManyToManyField(
        Frequency, related_name="consent_frequency", through="ConsentFrequency"
    )
    method = models.ManyToManyField(
        Method, related_name="consent_method", through="ConsentMethod"
    )
    show_checkbox = models.BooleanField(
        default=True,
        help_text=("Display a tick box on the enquiry form to confirm consent"),
    )
    message = models.TextField(
        default=(
            "Your phone number and email address will only be used to "
            "contact you in connection with this enquiry.  Please see our "
            "privacy notice for more information."
        ),
        help_text=(
            "Message explaining to the user why we are collecting their "
            "personal information on the enquiry form"
        ),
    )
    consent_required = models.BooleanField(
        default=False,
        help_text="User must tick the box before submitting the form",
    )
    no_consent_message = models.TextField(
        blank=True,
        default=(
            "Sorry, we will not be able to answer your enquiry "
            "unless you tick the box below to give us permission to use "
            "either your email address or phone number."
        ),
        help_text=(
            "Message explaining to the user why they need to tick the box "
            "(if they didn't)"
        ),
    )
    objects = ConsentManager()

    class Meta:
        ordering = ["name"]
        verbose_name = "Consent"
        verbose_name_plural = "Consent"

    def __str__(self):
        return "{} ('{}')".format(self.name, self.slug)

    def get_frequencies(self):
        return ConsentFrequency.objects.frequencies(self)

    def get_methods(self):
        return ConsentMethod.objects.methods(self)

    def unsubscribe_caption(self):
        """Caption for the submit button on the unsubscribe template."""
        return "Unsubscribe from {}".format(self.name)


reversion.register(Consent)


class ConsentFormSettings(models.Model):
    """Settings for displaying a consent form.

    Just pass the ``form_notice`` to the context and the standard
    ``_form.html`` template will display it.  This can be done by including
    ``ConsentMaintenanceMixin`` and setting ``consent_form_settings`` on your
    View.

    .. tip:: For the future, it might be worth adding a list of ``Consent``
             objects to this model so we can automatically create the consent
             section of the form.

    """

    slug = models.SlugField(unique=True)
    form_notice = models.TextField(
        help_text=(
            "A notice which can be passed to a form. "
            "Will normally be displayed just above the submit button. "
            "The text will be displayed with 'autoescape off', so you can "
            "include URLs."
        )
    )

    class Meta:
        ordering = ["slug"]
        verbose_name = "Consent Form Settings"
        verbose_name_plural = "Consent Form Settings"

    def __str__(self):
        return "{}".format(self.slug)


class ConsentFrequencyManager(models.Manager):
    def create_consent_frequency(self, consent, frequency):
        obj = self.model(consent=consent, frequency=frequency)
        obj.save()
        return obj

gdpr/templates/gdpr/_unsubscribe.html
{% if is_valid_user_consent %}
  <i class="fa fa-info-circle"></i>
  {% if userconsent.consent_given %}
    Click on the button to unsubscribe from
    <strong>
      {{ userconsent.consent.name }}
    </strong>
    {% include '_form.html' with submit=userconsent.consent.unsubscribe_caption %}
  {% else %}
    You have been unsubscribed from {{ userconsent.consent.name }}.
  {% endif %}
{% else %}
  <i class="fa fa-warning"></i>
  Sorry, we cannot find this unsubscribe request.
  <br>
  <a href="{% url 'web.contact' %}">
    Please contact us by clicking on this link...
  </a>
{% endif %}

gdpr/templates/gdpr/_user_consent_list.html
{% if consent_list %}
  <div class="pure-g">
    <div class="pure-u-1">
      <table class="pure-table pure-table-bordered" width="100%">
        <thead>
          <tr valign="top">
            <th>Consent Type</th>
            <th>Consent given?</th>
            <th>Date</th>
            <th>Updated By</th>
            <th>Comment</th>
            <th>Audit</th>
          </tr>
        </thead>
        <tbody>
          {% for x in consent_list %}
            <tr valign="top">
              <td>
                {{ x.consent.name }}
              </td>
              <td>
                <a href="{% url 'gdpr.user.consent.update' x.pk %}">
                  <i class="fa fa-edit"></i>
                  {% if x.consent_given %}
                    Yes
                  {% else %}
                    No
                  {% endif %}
                </a>
              </td>
              <td>
                {{ x.date_updated|date:'d/m/Y H:i' }}
              </td>
              <td>
                {% if x.user_updated %}
                  {{ x.user_updated.get_full_name }}
                  <small>
                    {{ x.user_updated.username }}
                  </small>
                {% endif %}
              </td>
              <td>
                {{ x.comment }}
              </td>
              <td>
                <a href="{% url 'gdpr.user.consent.audit.list' x.pk %}">
                  <i class="fa fa-history"></i>
                  Audit
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endif %}
{% if not object.deleted %}
  <div class="pure-menu pure-menu-horizontal">
    <ul class="pure-menu-list">
      <li class="pure-menu-item">
        <a href="{% url 'gdpr.user.consent.create' consent_user.pk %}" class="pure-menu-link">
          <i class="fa fa-plus"></i>
          Add Consent
        </a>
      </li>
    </ul>
  </div>
{% endif %}

gdpr/templates/gdpr/consent_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  Consent
{% endblock sub_title %}

{% block sub_heading %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  Consent
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            {% if object %}
              <a href="{% url 'gdpr.consent.detail' object.pk %}" class="pure-menu-link">
                <i class="fa fa-reply"></i>
              </a>
            {% else %}
              <a href="{% url 'gdpr.consent.list' %}" class="pure-menu-link">
                <i class="fa fa-reply"></i>
              </a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% include '_form.html' %}
    </div>
  </div>
{% endblock %}

{% block script_extra %}
  {{ block.super }}
  {% include 'base/_chosen.html' %}
{% endblock script_extra %}

gdpr/templates/gdpr/consent_list.html
{% extends 'dash/base.html' %}
{% load static %}

{% block title %}
  Consent Types
{% endblock title %}

{% block sub_heading %}
  Consent Types
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'project.settings' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.consent.create' %}" class="pure-menu-link">
              <i class="fa fa-plus"></i>
              Create Consent
            </a>
          </li>
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <table class="pure-table pure-table-bordered" width="100%">
        <thead>
          <tr>
            <th>Name</th>
            {% if gdpr_settings.show_frequency %}
              <th>Frequency</th>
            {% endif %}
            {% if gdpr_settings.show_method %}
              <th>Method</th>
            {% endif %}
            <th>Created</th>
          </tr>
        </thead>
        <tbody>
          {% for o in object_list %}
            <tr valign="top">
              <td>
                <a href="{% url 'gdpr.consent.detail' o.pk %}">
                  {{ o.name }}
                </a>
              </td>
              {% if gdpr_settings.show_frequency %}
                <td>
                  {% for x in o.get_frequencies %}
                    {{ x.frequency.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </td>
              {% endif %}
              {% if gdpr_settings.show_method %}
                <td>
                  {% for x in o.get_methods %}
                    {{ x.method.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </td>
              {% endif %}
              <td>
                {{ o.created|date:'d/m/Y H:i' }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}

gdpr/templates/gdpr/consentformsettings_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Form Settings
{% endblock sub_title %}

{% block sub_heading %}
  Form Settings
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.form.settings.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% include '_form.html' %}
    </div>
  </div>
{% endblock %}

{% block script_extra %}
  {{ block.super }}
  {% include 'base/_ckeditor.html' with id_textarea='id_form_notice' %}
{% endblock script_extra %}

gdpr/templates/gdpr/consentformsettings_list.html
{% extends 'dash/base.html' %}
{% load static %}

{% block title %}
  Form Settings
{% endblock title %}

{% block sub_heading %}
  Form Settings
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'project.settings' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.form.settings.create' %}" class="pure-menu-link">
              <i class="fa fa-plus"></i>
              Create Form Settings
            </a>
          </li>
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <table class="pure-table pure-table-bordered" width="100%">
        <thead>
          <tr>
            <th>Name</th>
            <th>Form Notice</th>
          </tr>
        </thead>
        <tbody>
          {% for o in object_list %}
            <tr valign="top">
              <td>
                <a href="{% url 'gdpr.form.settings.update' o.pk %}">
                  <i class="fa fa-edit"></i>
                  {{ o.slug }}
                </a>
              </td>
              <td>
                {% autoescape off %}
                  {{ o.form_notice }}
                {% endautoescape %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}

gdpr/templates/gdpr/frequency_delete_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Delete {{ object.name }}
  Communication Frequency
{% endblock sub_title %}

{% block sub_heading %}
  Delete {{ object.name }}
  Communication Frequency
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.method.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      Are you sure you want to delete the
      <strong>{{ object.name }}</strong>
      communication frequency?
      {% include '_form.html' with submit="Delete Communication Frequency" %}
    </div>
  </div>
{% endblock %}

gdpr/templates/gdpr/frequency_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  Communication Frequency
{% endblock sub_title %}

{% block sub_heading %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  Communication Frequency
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.frequency.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% include '_form.html' %}
    </div>
  </div>
{% endblock %}

gdpr/templates/gdpr/method_delete_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Delete {{ object.name }}
  Communication Method
{% endblock sub_title %}

{% block sub_heading %}
  Delete {{ object.name }}
  Communication Method
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.method.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      Are you sure you want to delete the
      <strong>{{ object.name }}</strong>
      communication method?
      {% include '_form.html' with method="POST" submit="Delete Communication Method" %}
    </div>
  </div>
{% endblock %}

gdpr/templates/gdpr/method_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  Communication Method
{% endblock sub_title %}

{% block sub_heading %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  Communication Method
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.method.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% include '_form.html' with method="POST" %}
    </div>
  </div>
{% endblock %}

gdpr/templates/gdpr/method_list.html
{% extends 'dash/base.html' %}
{% load static %}

{% block title %}
  Communication Methods
{% endblock title %}

{% block sub_heading %}
  Communication Methods
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'project.settings' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
          <li class="pure-menu-item">
            <a href="{% url 'gdpr.method.create' %}" class="pure-menu-link">
              <i class="fa fa-plus"></i>
              Create Communication Method
            </a>
          </li>
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <table class="pure-table pure-table-bordered" width="100%">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for o in object_list %}
            <tr valign="top">
              <td>
                <a href="{% url 'gdpr.method.update' o.pk %}">
                  <i class="fa fa-edit"></i>
                  {{ o.name }}
                </a>
                <small>
                  ({{ o.slug }})
                </small>
              </td>
              <td>
                {{ o.description }}
              </td>
              <td>
                {{ o.created|date:'d/m/Y H:i' }}
              </td>
              <td>
                <a href="{% url 'gdpr.method.delete' o.pk %}">
                  <i class="fa fa-trash-o"></i>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}

gdpr/templates/gdpr/userconsent_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  consent for {{ consent_user.get_full_name }}
  {% if object %}
    - {{ object.consent.name }}
  {% endif %}
{% endblock sub_title %}

{% block sub_heading %}
  {% if object %}
    Update
  {% else %}
    Create
  {% endif %}
  consent for {{ consent_user.get_full_name }}
  {% if object %}
    - {{ object.consent.name }}
  {% endif %}
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            {% if next %}
              <a href="{{ next }}" class="pure-menu-link">
                <i class="fa fa-reply"></i>
              </a>
            {% else %}
              <a href="{% url 'user.redirect.contact' consent_user.pk %}" class="pure-menu-link">
                <i class="fa fa-reply"></i>
              </a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% if object %}
        Update
      {% else %}
        Create
      {% endif %}
      consent for {{ consent_user.get_full_name }}
      {% if object %}
        -
        <strong>{{ object.consent.name }}</strong>
      {% endif %}
      {% include '_form.html' %}
    </div>
  </div>
{% endblock %}

{% block script_extra %}
  {{ block.super }}
  {% include 'base/_chosen.html' %}
{% endblock script_extra %}